// <auto-generated />
using FABRADE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FABRADE.Migrations
{
    [DbContext(typeof(fabradeDBContext))]
    partial class fabradeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FABRADE.Models.fabradeTransaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("age")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("contact_name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("contact_no")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dress_type")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("size")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("fabradeTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
